[package]
name = "autopy"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]

[lib]
## Python extension modules should be compiled as 'cdylib'
crate-type = ["cdylib"]
name = "autopy"

[dependencies.autopilot]
git = "https://github.com/autopilot-rs/autopilot-rs.git"

[dependencies.pyo3]
version = "0.2.6"
default-features = false

[dependencies.image]
image = "0.19"

[dependencies.either]
version = "1.5.0"
