[package]
name = "autopy"
version = "0.1.0"
authors = ["Michael Sanders <michael.sanders@fastmail.com>"]

[lib]
## Python extension modules should be compiled as 'cdylib'
crate-type = ["cdylib"]
name = "autopy"

[dependencies.autopilot]
version = "0.1.3"

[dependencies.pyo3]
version = "0.2.7"
default-features = false

[dependencies.image]
version = "0.19"

[dependencies.either]
version = "1.5.0"
